export default {
	modalTitle: "Nous utilisons des cookies",
	noticeText: "Nous utilisons des cookies et d'autres technologies de suivi pour améliorer votre expérience de navigation sur notre site, pour vous montrer un contenu personnalisé et des publicités ciblées, pour analyser le trafic de notre site et pour comprendre la provenance de nos visiteurs. En naviguant sur notre site Web, vous consentez à notre utilisation des cookies et autres technologies de suivi. Pour obtenir plus d'informations sur ces cookies, comment et pourquoi nous les utilisons et comment vous pouvez modifier vos paramètres, consultez notre <a href=\"{{cookiesPolicyLink}}\" target=\"_blank\">Politique relative aux cookies</a>. ", // {{cookiesPolicyLink}}
	btnAcceptAll: "Acceptez tous les cookies",
	btnManageCookies: "Gérer les cookies",
	btnAcceptSelection: "Accepter les cookies sélectionnés",
	privacyTitle: "Votre confidentialité est importante pour nous",
	privacyTextDefinition: "Les cookies sont de très petits fichiers texte qui sont stockés sur votre ordinateur lorsque vous visitez un site Web. Nous utilisons des cookies à diverses fins et pour améliorer votre expérience en ligne sur notre site Web (par exemple, pour mémoriser les informations de connexion de votre compte).",
	privacyTextInstructions: "Vous pouvez modifier vos préférences et refuser l'enregistrement de certains types de cookies sur votre ordinateur lors de la navigation sur notre site. Vous pouvez également supprimer les cookies déjà stockés sur votre ordinateur, mais gardez à l'esprit que leur suppression peut vous empêcher d'utiliser des éléments de notre site Web.",
	strictlyNecessaryTitle: "Cookies strictement nécessaires",
	strictlyNecessaryText: "Ces cookies sont essentiels pour vous fournir les services disponibles sur notre site Web et vous permettre d’utiliser certaines fonctionnalités de notre site Web. Sans ces cookies, nous ne pouvons pas vous fournir certains services sur notre site Web.",
	functionalityTitle: "Cookies de Fonctionnalité",
	functionalityText: "Ces cookies servent à vous offrir une expérience plus personnalisée sur notre site Web et à mémoriser les choix que vous faites lorsque vous utilisez notre site Web. Par exemple, nous pouvons utiliser des cookies de fonctionnalité pour mémoriser vos préférences de langue ou vos identifiants de connexion.",
	trackingTitle: "Cookies de suivi et de performance",
	trackingText: "Ces cookies sont utilisés pour collecter des informations permettant d'analyser le trafic sur notre site et la manière dont les visiteurs utilisent notre site. Par exemple, ces cookies peuvent suivre des choses telles que le temps que vous passez sur le site Web ou les pages que vous visitez, ce qui nous aide à comprendre comment nous pouvons améliorer notre site Web pour vous.",
	targetingTitle: "Cookies de ciblage et de publicité",
	targetingText: "Ces cookies sont utilisés pour afficher des publicités susceptibles de vous intéresser en fonction de vos habitudes de navigation. Ces cookies, tels que servis par nos fournisseurs de contenu et / ou de publicité, peuvent associer des informations qu'ils ont collectées sur notre site Web à d'autres informations qu'ils ont collectées de manière indépendante et concernant les activités du votre navigateur Web sur son réseau de sites Web. Si vous choisissez de supprimer ou de désactiver ces cookies de ciblage ou de publicité, vous verrez toujours des annonces, mais elles risquent de ne pas être pertinentes.",
};